/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as EligibilityCheckerRouteImport } from './routes/eligibility-checker'
import { Route as EligibilityResultsRouteImport } from './routes/eligibility-results'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SchemesRouteImport } from './routes/schemes'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as CategoriesIndexRouteImport } from './routes/categories.index'
import { Route as CategoriesCategoryRouteImport } from './routes/categories.$category'
import { Route as ResourcesIndexRouteImport } from './routes/resources.index'
import { Route as ResourcesHowToApplyForGovernmentSchemesRouteImport } from './routes/resources.how-to-apply-for-government-schemes'
import { Route as SchemeSlugRouteImport } from './routes/scheme.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityCheckerRoute = EligibilityCheckerRouteImport.update({
  id: '/eligibility-checker',
  path: '/eligibility-checker',
  getParentRoute: () => rootRouteImport,
} as any)
const EligibilityResultsRoute = EligibilityResultsRouteImport.update({
  id: '/eligibility-results',
  path: '/eligibility-results',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SchemesRoute = SchemesRouteImport.update({
  id: '/schemes',
  path: '/schemes',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesIndexRoute = CategoriesIndexRouteImport.update({
  id: '/categories/',
  path: '/categories/',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriesCategoryRoute = CategoriesCategoryRouteImport.update({
  id: '/categories/$category',
  path: '/categories/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesIndexRoute = ResourcesIndexRouteImport.update({
  id: '/resources/',
  path: '/resources/',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesHowToApplyForGovernmentSchemesRoute =
  ResourcesHowToApplyForGovernmentSchemesRouteImport.update({
    id: '/resources/how-to-apply-for-government-schemes',
    path: '/resources/how-to-apply-for-government-schemes',
    getParentRoute: () => rootRouteImport,
  } as any)
const SchemeSlugRoute = SchemeSlugRouteImport.update({
  id: '/scheme/$slug',
  path: '/scheme/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/eligibility-checker': typeof EligibilityCheckerRoute
  '/eligibility-results': typeof EligibilityResultsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/resources/how-to-apply-for-government-schemes': typeof ResourcesHowToApplyForGovernmentSchemesRoute
  '/scheme/$slug': typeof SchemeSlugRoute
  '/categories/': typeof CategoriesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/eligibility-checker': typeof EligibilityCheckerRoute
  '/eligibility-results': typeof EligibilityResultsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/resources/how-to-apply-for-government-schemes': typeof ResourcesHowToApplyForGovernmentSchemesRoute
  '/scheme/$slug': typeof SchemeSlugRoute
  '/categories': typeof CategoriesIndexRoute
  '/resources': typeof ResourcesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof DashboardRoute
  '/disclaimer': typeof DisclaimerRoute
  '/eligibility-checker': typeof EligibilityCheckerRoute
  '/eligibility-results': typeof EligibilityResultsRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/schemes': typeof SchemesRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/categories/$category': typeof CategoriesCategoryRoute
  '/resources/how-to-apply-for-government-schemes': typeof ResourcesHowToApplyForGovernmentSchemesRoute
  '/scheme/$slug': typeof SchemeSlugRoute
  '/categories/': typeof CategoriesIndexRoute
  '/resources/': typeof ResourcesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/disclaimer'
    | '/eligibility-checker'
    | '/eligibility-results'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/schemes'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/categories/$category'
    | '/resources/how-to-apply-for-government-schemes'
    | '/scheme/$slug'
    | '/categories/'
    | '/resources/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/disclaimer'
    | '/eligibility-checker'
    | '/eligibility-results'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/schemes'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/categories/$category'
    | '/resources/how-to-apply-for-government-schemes'
    | '/scheme/$slug'
    | '/categories'
    | '/resources'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/dashboard'
    | '/disclaimer'
    | '/eligibility-checker'
    | '/eligibility-results'
    | '/forgot-password'
    | '/how-it-works'
    | '/login'
    | '/privacy'
    | '/reset-password'
    | '/schemes'
    | '/signup'
    | '/sitemap.xml'
    | '/terms'
    | '/categories/$category'
    | '/resources/how-to-apply-for-government-schemes'
    | '/scheme/$slug'
    | '/categories/'
    | '/resources/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  DashboardRoute: typeof DashboardRoute
  DisclaimerRoute: typeof DisclaimerRoute
  EligibilityCheckerRoute: typeof EligibilityCheckerRoute
  EligibilityResultsRoute: typeof EligibilityResultsRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SchemesRoute: typeof SchemesRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  CategoriesCategoryRoute: typeof CategoriesCategoryRoute
  ResourcesHowToApplyForGovernmentSchemesRoute: typeof ResourcesHowToApplyForGovernmentSchemesRoute
  SchemeSlugRoute: typeof SchemeSlugRoute
  CategoriesIndexRoute: typeof CategoriesIndexRoute
  ResourcesIndexRoute: typeof ResourcesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility-checker': {
      id: '/eligibility-checker'
      path: '/eligibility-checker'
      fullPath: '/eligibility-checker'
      preLoaderRoute: typeof EligibilityCheckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eligibility-results': {
      id: '/eligibility-results'
      path: '/eligibility-results'
      fullPath: '/eligibility-results'
      preLoaderRoute: typeof EligibilityResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/schemes': {
      id: '/schemes'
      path: '/schemes'
      fullPath: '/schemes'
      preLoaderRoute: typeof SchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/': {
      id: '/categories/'
      path: '/categories'
      fullPath: '/categories/'
      preLoaderRoute: typeof CategoriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categories/$category': {
      id: '/categories/$category'
      path: '/categories/$category'
      fullPath: '/categories/$category'
      preLoaderRoute: typeof CategoriesCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/': {
      id: '/resources/'
      path: '/resources'
      fullPath: '/resources/'
      preLoaderRoute: typeof ResourcesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources/how-to-apply-for-government-schemes': {
      id: '/resources/how-to-apply-for-government-schemes'
      path: '/resources/how-to-apply-for-government-schemes'
      fullPath: '/resources/how-to-apply-for-government-schemes'
      preLoaderRoute: typeof ResourcesHowToApplyForGovernmentSchemesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scheme/$slug': {
      id: '/scheme/$slug'
      path: '/scheme/$slug'
      fullPath: '/scheme/$slug'
      preLoaderRoute: typeof SchemeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  DashboardRoute: DashboardRoute,
  DisclaimerRoute: DisclaimerRoute,
  EligibilityCheckerRoute: EligibilityCheckerRoute,
  EligibilityResultsRoute: EligibilityResultsRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SchemesRoute: SchemesRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  CategoriesCategoryRoute: CategoriesCategoryRoute,
  ResourcesHowToApplyForGovernmentSchemesRoute:
    ResourcesHowToApplyForGovernmentSchemesRoute,
  SchemeSlugRoute: SchemeSlugRoute,
  CategoriesIndexRoute: CategoriesIndexRoute,
  ResourcesIndexRoute: ResourcesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
